-- ============================================================================
-- DEPRECATED · Histórico — NO aplicar este archivo.
-- ============================================================================
--
-- La versión canónica y aplicable de esta migración vive en:
--   prisma/migrations/20260511000000_app_user_role_activation_ready/migration.sql
--
-- Este archivo se conservó solo para mantener el patrón histórico del
-- directorio `manual_migrations/`. Su contenido original incluía
-- `ALTER ROLE app_user NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS`,
-- que Supabase bloquea vía supautils. La versión real omite ese ALTER
-- porque los defaults de `CREATE ROLE x NOLOGIN` ya son seguros
-- (NOSUPERUSER, NOCREATEDB, NOCREATEROLE, NOBYPASSRLS por default).
--
-- Si vas a re-aplicar manualmente la migración en Supabase, copiar el
-- SQL de la ruta canónica, NO desde acá.
--
-- Verificación post-Fase 13 (docs/audits/phase-13-verification.md, O2)
-- detectó la discrepancia y reemplazó el contenido por este puntero.
